# Generated by Django 3.0.6 on 2020-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermission',
            name='permission',
            field=models.CharField(choices=[('V', 'View'), ('E', 'Edit'), ('D', 'Downstream')], max_length=1),
        ),
        migrations.AlterField(
            model_name='folderpermission',
            name='permission',
            field=models.CharField(choices=[('V', 'View'), ('E', 'Edit'), ('D', 'Downstream')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hostedservicefilepermission',
            name='permission',
            field=models.CharField(choices=[('V', 'View'), ('E', 'Edit'), ('D', 'Downstream')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hostedservicefolderpermission',
            name='permission',
            field=models.CharField(choices=[('V', 'View'), ('E', 'Edit'), ('D', 'Downstream')], max_length=1),
        ),
    ]
