# Generated by Django 2.2.4 on 2019-10-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedServiceFilePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('V', 'View'), ('E', 'Edit')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='cdrivefile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdrivefolder',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HostedServiceFolderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('V', 'View'), ('E', 'Edit')], max_length=1)),
                ('cdrive_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedservicefolderpermission_folder', to='drive_api.CDriveFolder')),
            ],
        ),
    ]
