# Generated by Django 2.2.4 on 2019-10-17 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0001_initial'),
        ('user_mgmt', '0001_initial'),
        ('drive_api', '0002_auto_20191017_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedservicefolderpermission',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedservicefolderpermission_service', to='services_api.HostedService'),
        ),
        migrations.AddField(
            model_name='hostedservicefolderpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedservicefolderpermission_user', to='user_mgmt.CDriveUser'),
        ),
        migrations.AddField(
            model_name='hostedservicefilepermission',
            name='cdrive_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedservicefilepermission_file', to='drive_api.CDriveFile'),
        ),
        migrations.AddField(
            model_name='hostedservicefilepermission',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedservicefilepermission_service', to='services_api.HostedService'),
        ),
        migrations.AddField(
            model_name='hostedservicefilepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedservicefilepermission_user', to='user_mgmt.CDriveUser'),
        ),
    ]
